export { default as Solve } from './Solve/Solve';
export { default as Home } from './Home/Home';
export { default as Result } from './Result/Result';
export { default as Problems } from './Problems/Problems';
export { default as NewQuestion } from './NewQuestion/NewQuestion';
export { default as Login } from './Login/Login';
export { default as Submitted } from './Submitted/Submitted';
export { default as SubmittedDetail } from './SubmittedDetail/SubmittedDetail';
export { default as Console } from './Console/Console';
